server:
  port: 8080
  servlet:
    context-path: /studentapp
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/student_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default:
          schema: student_db
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
